//! `ct-video-call-grant` -- mints the operator-signed [`ct_common::channel::ChannelGrant`]s
//! the video-conferencing browser demo needs (next increment after the browser-side join
//! primitives `holderSign`/`buildChannelJoinRequest` in `ct-agent-wasm`).
//!
//! A browser peer cannot mint its own grant -- that needs the channel **operator's** private
//! key, which must never reach the browser. This offline CLI plays the operator's part for a
//! demo: given two holder public keys (each browser tab's `HolderIdentity.public_hex`, from
//! `ct-agent-wasm`'s `generate_holder_identity()`), it locally signs one
//! [`ct_common::channel::SignedChannelGrant`] per holder for the deterministic
//! `channel_id_for_link(operator, holder_a, holder_b)` -- the exact id a browser peer
//! independently computes via its own `channel_id_for_link()` wasm export, no coordination
//! round-trip needed.
//!
//! This performs **no network call**: minting a grant is pure local signing. Registering the
//! resulting channel + holders with the live control plane (`POST /me/channels`, then
//! `POST /me/channels/:channel/members` for each holder, both owner-authenticated) so the
//! edge's `ChannelAuthorizer` actually recognizes them as members is a separate, credentialed
//! step -- deliberately not bundled into this tool, which never needs a network connection or
//! an OIDC session.
//!
//! Usage:
//!   ct-video-call-grant <holder_a_hex> <holder_b_hex> [--operator-private <hex>] [--ttl-secs <n>]
//!
//! Prints, one line per field:
//!   operator_public_hex=<...>   (register this exact channel with POST /me/channels)
//!   channel_id_hex=<...>
//!   grant_a_hex=<...>           (hand to holder A's browser tab)
//!   grant_b_hex=<...>           (hand to holder B's browser tab)

use ct_common::channel::{channel_id_for_link, ChannelGrant, Direction, Rights, SignedChannelGrant};
use ed25519_dalek::{Signer, SigningKey};

const DEFAULT_TTL_SECS: u64 = 3600;

struct Args {
    holder_a: [u8; 32],
    holder_b: [u8; 32],
    operator_private: Option<[u8; 32]>,
    ttl_secs: u64,
}

fn hex(bytes: &[u8]) -> String {
    bytes.iter().map(|b| format!("{b:02x}")).collect()
}

fn from_hex32(s: &str) -> Result<[u8; 32], String> {
    if s.len() != 64 {
        return Err(format!("expected 64 hex chars (32 bytes), got {}", s.len()));
    }
    let mut out = [0u8; 32];
    for (i, b) in out.iter_mut().enumerate() {
        *b = u8::from_str_radix(&s[2 * i..2 * i + 2], 16).map_err(|_| "invalid hex character".to_string())?;
    }
    Ok(out)
}

fn parse_args(raw: &[String]) -> Result<Args, String> {
    let mut positional = Vec::new();
    let mut operator_private = None;
    let mut ttl_secs = DEFAULT_TTL_SECS;
    let mut i = 0;
    while i < raw.len() {
        match raw[i].as_str() {
            "--operator-private" => {
                let v = raw.get(i + 1).ok_or("--operator-private needs a value")?;
                operator_private = Some(from_hex32(v).map_err(|e| format!("--operator-private: {e}"))?);
                i += 2;
            }
            "--ttl-secs" => {
                let v = raw.get(i + 1).ok_or("--ttl-secs needs a value")?;
                ttl_secs = v.parse::<u64>().map_err(|_| "--ttl-secs must be a positive integer".to_string())?;
                i += 2;
            }
            other => {
                positional.push(other.to_string());
                i += 1;
            }
        }
    }
    if positional.len() != 2 {
        return Err(format!(
            "expected exactly 2 positional args (holder_a_hex holder_b_hex), got {}",
            positional.len()
        ));
    }
    Ok(Args {
        holder_a: from_hex32(&positional[0]).map_err(|e| format!("holder_a_hex: {e}"))?,
        holder_b: from_hex32(&positional[1]).map_err(|e| format!("holder_b_hex: {e}"))?,
        operator_private,
        ttl_secs,
    })
}

struct MintedGrants {
    operator_public_hex: String,
    channel_id_hex: String,
    grant_a_hex: String,
    grant_b_hex: String,
}

/// The pure, testable core: given parsed args, an operator signing key (generated by the
/// caller if `args.operator_private` is `None`), and the current unix time, produce the two
/// signed grants. No I/O, no process exit -- kept separate from `main` so it's directly
/// unit-testable.
fn mint(args: &Args, operator_sk: &SigningKey, now: u64) -> MintedGrants {
    let operator_public = operator_sk.verifying_key().to_bytes();
    let channel = channel_id_for_link(&operator_public, &args.holder_a, &args.holder_b);
    let expires_at = now + args.ttl_secs;

    let sign_for = |holder: [u8; 32]| -> SignedChannelGrant {
        let grant = ChannelGrant { channel, holder, direction: Direction::Both, rights: Rights::ReadWrite, delegable: false, expires_at };
        let signature = operator_sk.sign(&grant.signing_bytes()).to_bytes();
        SignedChannelGrant { grant, signature }
    };

    MintedGrants {
        operator_public_hex: hex(&operator_public),
        channel_id_hex: hex(&channel.0),
        grant_a_hex: hex(&sign_for(args.holder_a).encode()),
        grant_b_hex: hex(&sign_for(args.holder_b).encode()),
    }
}

fn main() {
    let raw: Vec<String> = std::env::args().skip(1).collect();
    let args = match parse_args(&raw) {
        Ok(a) => a,
        Err(e) => {
            eprintln!("ct-video-call-grant: {e}");
            eprintln!("usage: ct-video-call-grant <holder_a_hex> <holder_b_hex> [--operator-private <hex>] [--ttl-secs <n>]");
            std::process::exit(2);
        }
    };
    let operator_sk = match args.operator_private {
        Some(bytes) => SigningKey::from_bytes(&bytes),
        None => SigningKey::generate(&mut rand::rngs::OsRng),
    };
    let now = std::time::SystemTime::now().duration_since(std::time::UNIX_EPOCH).expect("system clock before unix epoch").as_secs();
    let minted = mint(&args, &operator_sk, now);

    println!("operator_public_hex={}", minted.operator_public_hex);
    println!("channel_id_hex={}", minted.channel_id_hex);
    println!("grant_a_hex={}", minted.grant_a_hex);
    println!("grant_b_hex={}", minted.grant_b_hex);
}

#[cfg(test)]
mod tests {
    use super::*;
    use ct_common::channel::verify;

    fn args(holder_a: [u8; 32], holder_b: [u8; 32]) -> Args {
        Args { holder_a, holder_b, operator_private: None, ttl_secs: DEFAULT_TTL_SECS }
    }

    #[test]
    fn minted_grants_verify_against_the_real_ct_common_verify_and_carry_the_right_rights() {
        let operator_sk = SigningKey::generate(&mut rand::rngs::OsRng);
        let holder_a = [0x11u8; 32];
        let holder_b = [0x22u8; 32];
        let now = 1_000_000_000;

        let minted = mint(&args(holder_a, holder_b), &operator_sk, now);
        let operator_pub = operator_sk.verifying_key().to_bytes();

        let grant_a = SignedChannelGrant::decode(&hex_decode(&minted.grant_a_hex)).unwrap();
        let grant_b = SignedChannelGrant::decode(&hex_decode(&minted.grant_b_hex)).unwrap();

        assert!(verify(&operator_pub, &grant_a, now).is_ok());
        assert!(verify(&operator_pub, &grant_b, now).is_ok());
        assert_eq!(grant_a.grant.holder, holder_a);
        assert_eq!(grant_b.grant.holder, holder_b);
        assert_eq!(grant_a.grant.direction, Direction::Both);
        assert_eq!(grant_a.grant.rights, Rights::ReadWrite);
        assert!(!grant_a.grant.delegable);
        assert_eq!(grant_a.grant.expires_at, now + DEFAULT_TTL_SECS);

        // Both grants share the same channel id -- the deterministic link id, matching
        // exactly what a browser peer's own channel_id_for_link() wasm export computes.
        assert_eq!(grant_a.grant.channel, grant_b.grant.channel);
        assert_eq!(hex(&grant_a.grant.channel.0), minted.channel_id_hex);
        let expected_channel = channel_id_for_link(&operator_pub, &holder_a, &holder_b);
        assert_eq!(grant_a.grant.channel, expected_channel);
    }

    #[test]
    fn minted_grants_fail_verification_after_expiry() {
        let operator_sk = SigningKey::generate(&mut rand::rngs::OsRng);
        let holder_a = [0x33u8; 32];
        let holder_b = [0x44u8; 32];
        let now = 1_000_000_000;
        let minted = mint(&args(holder_a, holder_b), &operator_sk, now);
        let grant_a = SignedChannelGrant::decode(&hex_decode(&minted.grant_a_hex)).unwrap();
        let operator_pub = operator_sk.verifying_key().to_bytes();

        assert!(verify(&operator_pub, &grant_a, now + DEFAULT_TTL_SECS).is_err(), "must be expired at exactly expires_at");
    }

    #[test]
    fn a_grant_signed_by_a_different_operator_key_is_rejected() {
        let operator_sk = SigningKey::generate(&mut rand::rngs::OsRng);
        let other_sk = SigningKey::generate(&mut rand::rngs::OsRng);
        let minted = mint(&args([0x55u8; 32], [0x66u8; 32]), &operator_sk, 1_000_000_000);
        let grant_a = SignedChannelGrant::decode(&hex_decode(&minted.grant_a_hex)).unwrap();

        let wrong_pub = other_sk.verifying_key().to_bytes();
        assert!(verify(&wrong_pub, &grant_a, 1_000_000_000).is_err());
    }

    #[test]
    fn parse_args_accepts_the_operator_private_and_ttl_flags_in_either_order() {
        let a = [0xAAu8; 32];
        let b = [0xBBu8; 32];
        let raw = vec![
            hex(&a),
            "--ttl-secs".to_string(),
            "60".to_string(),
            hex(&b),
            "--operator-private".to_string(),
            hex(&[0x01u8; 32]),
        ];
        let parsed = parse_args(&raw).unwrap();
        assert_eq!(parsed.holder_a, a);
        assert_eq!(parsed.holder_b, b);
        assert_eq!(parsed.ttl_secs, 60);
        assert_eq!(parsed.operator_private, Some([0x01u8; 32]));
    }

    #[test]
    fn parse_args_rejects_bad_arity_and_bad_hex() {
        assert!(parse_args(&[hex(&[0u8; 32])]).is_err(), "only one positional arg");
        assert!(parse_args(&["not-hex".to_string(), hex(&[0u8; 32])]).is_err());
        assert!(parse_args(&["--ttl-secs".to_string(), "not-a-number".to_string(), hex(&[0u8; 32]), hex(&[1u8; 32])]).is_err());
    }

    fn hex_decode(s: &str) -> Vec<u8> {
        (0..s.len()).step_by(2).map(|i| u8::from_str_radix(&s[i..i + 2], 16).unwrap()).collect()
    }
}
